# Generated by Django 4.0.5 on 2022-06-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo1', '0002_aeropuerto_alter_vuelos_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('edad', models.IntegerField()),
                ('vuelos', models.ManyToManyField(blank=True, related_name='pasajero', to='modelo1.vuelos')),
            ],
        ),
    ]
